apiVersion: v1
kind: Service
metadata:
  name: microservice-1-svc
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: microservice-1
