apiVersion: v1
kind: Service
metadata:
  name: microservice-1-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30000
  selector:
    app: microservice-1