name: CI

on:
  push:
    paths:
      - 'microservices/microservice-1/**'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image
        run: |
          PATH_REGISTRY=${{ secrets.DOCKER_USERNAME }}/microservice-1
          DOCKERFILE_PATH=/microservices/microservice-1/Dockerfile
          docker build -f $DOCKERFILE_PATH -t $PATH_REGISTRY .
          docker push $PATH_REGISTRY
