name: CI

on:
  push:
    paths:
      - 'microservices/microservice-1/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          VERSION=${TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH + 1))
          NEW_TAG="v$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_TAG"
          echo "tag=$NEW_TAG" >> $GITHUB_ENV

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image
        run: |
          PATH_REGISTRY=${{ secrets.DOCKER_USERNAME }}/microservice-1
          DOCKERFILE_PATH=./microservices/microservice-1/Dockerfile
          TAG=${{ env.tag }}
          docker build -f $DOCKERFILE_PATH -t $PATH_REGISTRY:$TAG .
          docker push $PATH_REGISTRY:$TAG

      - name: Update Kubernetes Deployment File with New Image Version
        run: |
          sed -i "s|image: lioratari/microservice-1.*|image: lioratari/microservice-1:${{ env.tag }}|g" ./kubernetes/microservice-1/deployment.yaml

      - name: Commit updated file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if [[ $(git status --porcelain ]]; then
            git add ./kubernetes/microservice-1/deployment.yaml
            git commit -m "Update image version for microservice-1 to ${{ env.tag }}"
            git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/LiorAtari/aws-project.git
          else
            echo "No changes to commit"
          fi
      - name: Create and Push New Git Tag
        run: |
          git tag ${{ env.tag }}
          git push origin ${{ env.tag }}
